services:
  - type: web
    name: test-shop-backend
    env: node
    rootDir: server
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    disk:
      name: test-shop-db
      mountPath: /var/data
      sizeGB: 1

  - type: web
    name: test-shop-frontend
    env: node
    rootDir: client
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: test-shop-backend
          property: url
